[package]
name = "ivy-to-mypyvy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.26", features = ["derive"] }
pest = "2.4.1"
pest_derive = "2.4.1"
